module.exports = {
  "autoImports": [
    {
      "module": "monada-core",
      "value": [
        "typeof",
        "instanceof",
        "try",
        "throw",
        "new",
        "invoke",
        "==",
        "+",
        "-",
        "*",
        "/",
        "%",
        ">",
        "<",
        ">=",
        "<=",
        "~",
        "|",
        "&",
        "^",
        ">>",
        "<<",
        ">>>",
        "!",
        "||",
        "&&",
        "undefined",
        "null",
        "false",
        "true",

        "fromJS",
        "toJS",
        "size",
        "record",
        "list",
        "hashmap",
        "range",
        "getp",
        "hasp",
        "get",
        "getIn",
        "set",
        "setIn",
        "has",
        "var",
        "getv",
        "setv",
        "monad",
        "isMonad",
        "done",
        "isDone",
        "seq",
        "transduce",

        "map",
        "filter",
        "reduce",
        "take",

        "run",

        "$"
      ]
    }
  ]
};
