module.exports = {
  "autoImports": [
    {
      "module": "monada-core",
      "value": [
        "typeof",
        "instanceof",
        "try",
        "throw",
        "new",
        "invoke",
        "==",
        "+",
        "-",
        "*",
        "/",
        "%",
        ">",
        "<",
        ">=",
        "<=",
        "~",
        "|",
        "&",
        "^",
        ">>",
        "<<",
        ">>>",
        "!",
        "||",
        "&&",

        "fromJS",
        "toJS",
        "fromJSON",
        "toJSON",
        "size",
        "List",
        "Map",
        "record",
        "Monad",
        "Done",
        "hasp",
        "getp",
        "has",
        "hasIn",
        "get",
        "getIn",
        "update",
        "updateIn",
        "set",
        "setIn",
        "remove",
        "removeIn",
        "merge",
        "mergeDeep",
        "mergeWith",
        "mergeDeepWith",
        "isList",
        "isMap",
        "isRecord",
        "seq",
        "for",
        "var",

        "check",
        "aMap",
        "aFunction",

        "map",
        "filter",
        "reduce",
        "take",
        "indexed",

        "run",

        "$"
      ]
    }
  ]
};
